'use client';

import { useQuery } from '@tanstack/react-query';
import { apiFetch } from '@/lib/apiFetch';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { BrainCircuit, Search, Coins, Activity } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeaderCell,
  TableRow,
} from '@/components/ui/table';

export default function AiUsagePage() {
  const { data, isLoading } = useQuery({
    queryKey: ['aiUsage'],
    queryFn: () => apiFetch('/settings/ai-usage').then((r) => r.json()),
  });

  if (isLoading) {
    return <div className="p-8 text-center text-muted-foreground">Loading AI usage data...</div>;
  }

  const metrics = data?.metrics || { total_tokens: 0, total_cost_usd: 0, total_web_searches: 0 };
  const logs = data?.data || [];

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold tracking-tight">AI Usage & Cost Tracking</h2>
        <p className="text-sm text-muted-foreground mt-1">Monitor the token consumption and estimated cost generated by Leadsy's AI services.</p>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Tokens Used</CardTitle>
            <BrainCircuit className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{metrics.total_tokens.toLocaleString()}</div>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Est. Cost (USD)</CardTitle>
            <Coins className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">${metrics.total_cost_usd.toFixed(4)}</div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Google Grounding Hits</CardTitle>
            <Search className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{metrics.total_web_searches.toLocaleString()}</div>
            <p className="text-xs text-muted-foreground mt-1">Web search enabled queries</p>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Usage Logs</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHead>
              <TableRow>
                <TableHeaderCell>Time</TableHeaderCell>
                <TableHeaderCell>User</TableHeaderCell>
                <TableHeaderCell>Action</TableHeaderCell>
                <TableHeaderCell>Provider/Model</TableHeaderCell>
                <TableHeaderCell className="text-right">Tokens</TableHeaderCell>
                <TableHeaderCell className="text-right">Cost</TableHeaderCell>
                <TableHeaderCell className="text-center">Web Search</TableHeaderCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {logs.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={7} className="text-center py-6 text-muted-foreground">No AI usage recorded yet.</TableCell>
                </TableRow>
              ) : (
                logs.map((log: any) => (
                  <TableRow key={log.id}>
                    <TableCell className="whitespace-nowrap">{new Date(log.created_at).toLocaleString()}</TableCell>
                    <TableCell>{log.user?.name || 'System'}</TableCell>
                    <TableCell>
                      <Badge variant="outline">{log.action}</Badge>
                    </TableCell>
                    <TableCell>
                      <div className="text-sm font-medium">{log.provider}</div>
                      <div className="text-xs text-muted-foreground">{log.model}</div>
                    </TableCell>
                    <TableCell className="text-right">{log.tokens_total.toLocaleString()}</TableCell>
                    <TableCell className="text-right text-brand font-medium">${parseFloat(log.estimated_cost_usd).toFixed(4)}</TableCell>
                    <TableCell className="text-center">
                      {log.has_web_search ? <Badge variant="success">Yes</Badge> : <span className="text-muted-foreground">-</span>}
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
