export const tourSteps = [
  {
    id: "navigation",
    route: "/",
    target: "[data-tour='sidebar-nav']",
    title: "Main Navigation",
    content: "Use the sidebar to move between Dashboard, Map, Leads, Products, WhatsApp, and Settings. The available items follow your role permissions.",
    placement: "right",
    action: null,
    disableOverlay: false,
    spotlightPadding: 8,
  },
  {
    id: "global-search",
    route: "/",
    target: "[data-tour='global-search']",
    title: "Global Search",
    content: "This top search area keeps lookup close at hand while you work across the platform.",
    placement: "bottom",
    action: null,
    disableOverlay: false,
    spotlightPadding: 8,
  },
  {
    id: "dashboard-kpis",
    route: "/",
    target: "[data-tour='dashboard-kpis']",
    title: "Key Metrics",
    content: "Dashboard KPI cards summarize total leads, qualification, pipeline volume, and duplicate risk. Click a card to drill into the matching Leads view.",
    placement: "bottom",
    action: null,
    disableOverlay: false,
    spotlightPadding: 10,
  },
  {
    id: "dashboard-funnel",
    route: "/",
    target: "[data-tour='dashboard-funnel']",
    title: "Conversion Funnels",
    content: "The Won and Lost funnels are database-backed and clickable, so you can inspect the leads behind each pipeline stage.",
    placement: "top",
    action: null,
    disableOverlay: false,
    spotlightPadding: 10,
  },
  {
    id: "dashboard-map",
    route: "/",
    target: "[data-tour='dashboard-map']",
    title: "Lead Geography",
    content: "Mapped leads appear as stage-colored POI markers. Use this to understand territory coverage and geographic sales opportunities.",
    placement: "left",
    action: null,
    disableOverlay: false,
    spotlightPadding: 10,
  },
  {
    id: "dashboard-sources",
    route: "/",
    target: "[data-tour='dashboard-source-channel']",
    title: "Lead Sources & Channels",
    content: "This block aggregates lead origin by source and channel, with drilldowns into filtered lead lists.",
    placement: "top",
    action: null,
    disableOverlay: false,
    spotlightPadding: 10,
  },
  {
    id: "map-discovery",
    route: "/map",
    target: "[data-tour='map-discovery']",
    title: "Map & Territory Discovery",
    content: "Search businesses in a geographic radius, filter by product fit, and add high-potential leads directly to your pipeline from the map.",
    placement: "bottom",
    action: null,
    disableOverlay: false,
    spotlightPadding: 10,
  },
  {
    id: "review-queue",
    route: "/qualification/reviews",
    target: "[data-tour='review-queue']",
    title: "Human Verification Queue",
    content: "Review AI-scored leads before they advance in the pipeline. Approve, reject, hold, or override the score with a governance-backed decision trail.",
    placement: "bottom",
    action: null,
    disableOverlay: false,
    spotlightPadding: 10,
  },
  {
    id: "leads-actions",
    route: "/leads",
    target: "[data-tour='leads-actions']",
    title: "Lead Actions",
    content: "Create leads manually, import from Excel, export data, or jump into the review queue from this action group.",
    placement: "bottom",
    action: null,
    disableOverlay: false,
    spotlightPadding: 8,
  },
  {
    id: "leads-filters",
    route: "/leads",
    target: "[data-tour='leads-filters']",
    title: "Lead Filters",
    content: "Filter leads by stage, qualification, duplicate state, source, channel, and score range to focus your workflow.",
    placement: "bottom",
    action: null,
    disableOverlay: false,
    spotlightPadding: 8,
  },
  {
    id: "leads-table",
    route: "/leads",
    target: "[data-tour='leads-table']",
    title: "Lead Workspace",
    content: "The lead table combines company details, source/channel, score, revenue fields, stage movement, edit, WhatsApp, and detail navigation.",
    placement: "top",
    action: null,
    disableOverlay: false,
    spotlightPadding: 8,
  },
  {
    id: "products-ai",
    route: "/products",
    target: "[data-tour='products-add']",
    title: "AI-Assisted Products",
    content: "Products power matching and qualification. Add a product, then use AI Generate, Analyze URL, or Analyze PDF to fill product metadata.",
    placement: "bottom",
    action: null,
    disableOverlay: false,
    spotlightPadding: 8,
  },
  {
    id: "settings-master-data",
    route: "/settings",
    target: "[data-tour='settings-master-data']",
    title: "Master Data Settings",
    content: "Settings centralizes flexible master data such as lead sources, lead channels, lead stages, industries, ICP profiles, and AI defaults.",
    placement: "top",
    action: null,
    disableOverlay: false,
    spotlightPadding: 10,
  },
  {
    id: "tour-trigger",
    route: "/",
    target: "[data-tour='tour-trigger']",
    title: "Restart Anytime",
    content: "Use this button whenever you want to restart the tour from the beginning. Completion and minimized state are saved in this browser.",
    placement: "bottom",
    action: null,
    disableOverlay: false,
    spotlightPadding: 8,
  },
];
